export const SKILL_CATEGORIES = {
  PROGRAMMING_LANGUAGES: {
    name: "Programming Languages",
    skills: [
      { name: "JavaScript", iconClass: "devicon-javascript-plain colored" },
      { name: "Python", iconClass: "devicon-python-plain colored" },
      { name: "Java", iconClass: "devicon-java-plain colored" },
      { name: "C++", iconClass: "devicon-cplusplus-plain colored" },
      { name: "C#", iconClass: "devicon-csharp-plain colored" },
      { name: "TypeScript", iconClass: "devicon-typescript-plain colored" },
      { name: "Ruby", iconClass: "devicon-ruby-plain colored" },
      { name: "PHP", iconClass: "devicon-php-plain colored" },
      { name: "Swift", iconClass: "devicon-swift-plain colored" },
      { name: "Kotlin", iconClass: "devicon-kotlin-plain colored" },
      { name: "Go", iconClass: "devicon-go-plain colored" },
      { name: "Rust", iconClass: "devicon-rust-plain colored" },
      { name: "Dart", iconClass: "devicon-dart-plain colored" },
      { name: "Lua", iconClass: "devicon-lua-plain colored" },
      { name: "Scala", iconClass: "devicon-scala-plain colored" },
      { name: "Objective-C", iconClass: "devicon-c-plain" },
    ],
  },
  FRAMEWORKS: {
    name: "Frameworks & Libraries",
    skills: [
      { name: "React", iconClass: "devicon-react-original colored" },
      { name: "Node.js", iconClass: "devicon-nodejs-plain colored" },
      { name: "Angular", iconClass: "devicon-angularjs-plain colored" },
      { name: "Vue.js", iconClass: "devicon-vuejs-plain colored" },
      { name: "Django", iconClass: "devicon-django-plain colored" },
      { name: "Express", iconClass: "devicon-express-original colored" },
      { name: "Next.js", iconClass: "devicon-nextjs-plain colored" },
      { name: "Flask", iconClass: "devicon-flask-original colored" },
      { name: "Spring", iconClass: "devicon-spring-plain colored" },
      { name: "Laravel", iconClass: "devicon-laravel-plain colored" },
      { name: "Svelte", iconClass: "devicon-svelte-plain colored" },
      { name: "Ruby on Rails", iconClass: "devicon-rails-plain colored" },
      { name: "ASP.NET", iconClass: "devicon-dot-net-plain colored" },
      { name: "Flutter", iconClass: "devicon-flutter-plain colored" },
      { name: "Electron", iconClass: "devicon-electron-original colored" },
      { name: "NestJS", iconClass: "devicon-nestjs-plain colored" },
      { name: "FastAPI", iconClass: "devicon-fastapi-plain" },
      { name: "React Native", iconClass: "devicon-react-original colored" },
      { name: "Flutter", iconClass: "devicon-flutter-plain colored" },
      { name: "iOS Development", iconClass: "devicon-apple-original colored" },
      {
        name: "Android Development",
        iconClass: "devicon-android-plain colored",
      },
      { name: "Xamarin", iconClass: "devicon-xamarin-original colored" },
      { name: "Swift UI", iconClass: "devicon-swift-plain colored" },
      { name: "Jetpack Compose", iconClass: "devicon-kotlin-plain colored" },
      { name: "Firebase", iconClass: "devicon-firebase-plain colored" },
      { name: "Ionic", iconClass: "devicon-ionic-original colored" },
      { name: "Cordova", iconClass: "devicon-apache-plain colored" },
      { name: "Mobile UI Design", iconClass: "devicon-figma-plain" },
    ],
  },
  TOOLS: {
    name: "Tools & Software",
    skills: [
      { name: "Git", iconClass: "devicon-git-plain colored" },
      { name: "AWS", iconClass: "devicon-amazonwebservices-original colored" },
      { name: "MongoDB", iconClass: "devicon-mongodb-plain colored" },
      { name: "MySQL", iconClass: "devicon-mysql-plain colored" },
      { name: "PostgreSQL", iconClass: "devicon-postgresql-plain colored" },
      { name: "Figma", iconClass: "devicon-figma-plain colored" },
      { name: "Adobe XD", iconClass: "devicon-xd-plain colored" },
      { name: "Sketch", iconClass: "devicon-sketch-plain colored" },
      { name: "Illustrator", iconClass: "devicon-illustrator-plain colored" },
      { name: "Photoshop", iconClass: "devicon-photoshop-plain colored" },
      { name: "CSS", iconClass: "devicon-css3-plain colored" },
      { name: "Sass/SCSS", iconClass: "devicon-sass-original colored" },
      { name: "Redis", iconClass: "devicon-redis-plain colored" },
      { name: "TensorFlow", iconClass: "devicon-tensorflow-original colored" },
      { name: "PyTorch", iconClass: "devicon-pytorch-original colored" },
      { name: "Keras", iconClass: "devicon-keras-plain colored" },
      { name: "Scikit-learn", iconClass: "devicon-sklearn-plain colored" },
      { name: "Unity AR/VR", iconClass: "devicon-unity-original colored" },
      { name: "Unreal AR/VR", iconClass: "devicon-unrealengine-original" },
      { name: "Three.js", iconClass: "devicon-threejs-original colored" },
      { name: "AWS", iconClass: "devicon-amazonwebservices-original colored" },
      { name: "Google Cloud", iconClass: "devicon-googlecloud-plain colored" },
      { name: "Azure", iconClass: "devicon-azure-plain colored" },
      { name: "Kubernetes", iconClass: "devicon-kubernetes-plain colored" },
      { name: "Terraform", iconClass: "devicon-terraform-plain colored" },
      { name: "CI/CD", iconClass: "devicon-jenkins-plain colored" },
      { name: "SQL", iconClass: "devicon-mysql-plain colored" },
      { name: "PostgreSQL", iconClass: "devicon-postgresql-plain colored" },
      { name: "Redis", iconClass: "devicon-redis-plain colored" },
      { name: "Cassandra", iconClass: "devicon-cassandra-plain colored" },
      { name: "GraphQL", iconClass: "devicon-graphql-plain colored" },
    ],
  },
  DEV_TOOLS: {
    name: "Development Tools",
    skills: [
      { name: "Git", iconClass: "devicon-git-plain colored" },
      { name: "GitHub", iconClass: "devicon-github-original colored" },
      { name: "VS Code", iconClass: "devicon-vscode-plain colored" },
      { name: "JetBrains Suite", iconClass: "devicon-jetbrains-plain colored" },
      { name: "Webpack", iconClass: "devicon-webpack-plain colored" },
      { name: "Babel", iconClass: "devicon-babel-plain colored" },
      { name: "Jest", iconClass: "devicon-jest-plain colored" },
      { name: "npm", iconClass: "devicon-npm-original-wordmark colored" },
      { name: "Yarn", iconClass: "devicon-yarn-plain colored" },
      { name: "Jira", iconClass: "devicon-jira-plain colored" },
      { name: "GitLab", iconClass: "devicon-gitlab-plain colored" },
      { name: "Bitbucket", iconClass: "devicon-bitbucket-original colored" },
      { name: "Postman" },
      { name: "Docker", iconClass: "devicon-docker-plain colored" },
      { name: "Nginx", iconClass: "devicon-nginx-original colored" },
      { name: "Jupyter", iconClass: "devicon-jupyter-plain colored" },
    ],
  },
  SOFT_SKILLS: {
    name: "Professional Skills",
    skills: [
      { name: "Project Management" },
      { name: "Agile Methodology" },
      { name: "Scrum" },
      { name: "Kanban" },
      { name: "Team Leadership" },
      { name: "Problem Solving" },
      { name: "System Design" },
      { name: "Technical Writing" },
      { name: "Code Review" },
      { name: "Mentoring" },
      { name: "Technical Presentations" },
      { name: "Requirements Analysis" },
      { name: "Cross-functional Collaboration" },
      { name: "Continuous Improvement" },
      { name: "Test-Driven Development" },
      { name: "Software Architecture" },
    ],
  },
};
